const position = { x: 0, y: 0 };
const edgeType = "smoothstep";
export const initNodesData = [
  {
    id: "1",
    type: "turbo",
    data: {
      name: "someone...",
      birthDate: "15 Jun 1925",
      bornIn: "Palermo, IT",
      events: [],
      gender: "Male",
    },
    recordToOrder: ["Birth", "Naturalization", "Death"],
    countryCode: "IT",
    position,
  },
  {
    id: "2",
    type: "turbo",
    data: {
      name: "someone...",
      birthDate: "30 Aug 1927",
      bornIn: "California, US",
      events: [],
      gender: "Female",
    },
    recordToOrder: ["Birth", "Marriage"],
    countryCode: "IT",
    position,
  },
  {
    id: "3",
    type: "turbo",
    data: {
      name: "someone...",
      birthDate: "23 May 1946",
      bornIn: "Ohio, US",
      events: [],
      gender: "Male",
    },
    recordToOrder: ["Birth"],
    countryCode: "IT",
    position,
  },
  {
    id: "4",
    type: "turbo",
    data: {
      name: "someone...",
      birthDate: "23 Jan 1945",
      bornIn: "California, US",
      events: [],
      gender: "Female",
    },
    recordToOrder: ["Birth", "Marriage", "Divorce"],
    countryCode: "IT",
    position,
  },
  {
    id: "5",
    type: "turbo",
    data: {
      name: "someone...",
      birthDate: "31 Mar 1970",
      bornIn: "California, US",
      flag: true,
      events: [],
      gender: "Female",
    },
    recordToOrder: ["Birth", "Marriage", "Divorce"],
    countryCode: "IT",
    position,
  },
  {
    id: "6",
    type: "turbo",
    data: {
      name: "someone...",
      birthDate: "30 Jun 1973",
      bornIn: "California, US",
      flag: true,
      events: [],
      gender: "Male",
    },
    recordToOrder: ["Birth", "Marriage"],
    countryCode: "IT",
    position,
  },
  {
    id: "7",
    type: "turbo",
    data: {
      name: "someone...",
      birthDate: "20 Jan 2013",
      bornIn: "California, US",
      flag: true,
      events: [],
      gender: "Female",
    },
    recordToOrder: ["Birth"],
    countryCode: "IT",
    position,
  },
  {
    id: "8",
    type: "turbo",
    data: {
      name: "someone...",
      birthDate: "08 Jul 1972",
      bornIn: "Barranquilla, CO",
      events: [],
      gender: "Female",
    },
    recordToOrder: ["Birth"],
    countryCode: "IT",
    position,
  },
];

export const initEdgesData = [
  {
    id: "e13",
    source: "1",
    target: "3",
    type: edgeType,
  },
  {
    id: "e23",
    source: "2",
    target: "3",
    type: edgeType,
  },
  {
    id: "e35",
    source: "3",
    target: "5",
    type: edgeType,
  },

  {
    id: "e36",
    source: "3",
    target: "6",
    type: edgeType,
  },
  {
    id: "e37",
    source: "3",
    target: "7",
    type: edgeType,
  },
  {
    id: "e45",
    source: "4",
    target: "5",
    type: edgeType,
  },
  {
    id: "e46",
    source: "4",
    target: "6",
    type: edgeType,
  },
  {
    id: "e87",
    source: "8",
    target: "7",
    type: edgeType,
  },
];
